esphome:
  name: ${devicename}
  friendly_name: ${devicename_upper}

esp32:
  board: esp32doit-devkit-v1

packages:
  wifi: !include wifi.yaml

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename_upper} Fallback Hotspot"
    password: "gFtZZ79ce7iQ"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
