substitutions:
  devicename: bedroom
  devicename_upper: Bedroom

<<: !include ./.base32.yaml


## LED
light:
- platform: neopixelbus
  variant: WS2812X
  pin: GPIO33
  num_leds: 179
  name: "Full Strip"
  id: strip
  # Limit max brightness
  effects:
  - pulse:
      update_interval: 2s
      transition_length: 1s
      min_brightness: 15%
      max_brightness: 60%
  - addressable_rainbow:
      width: 179
  - addressable_color_wipe:
      name: Cyberpunk
      add_led_interval: 200ms
      colors:
      - red: 80%
        blue: 100%
        green: 0%
        white: 0%
        num_leds: 90
      - red: 0%
        blue: 100%
        green: 80%
        white: 0%
        num_leds: 90
  - addressable_color_wipe:
      name: Police
      add_led_interval: 50ms
      colors:
      - red: 100%
        blue: 0%
        green: 0%
        white: 0%
        num_leds: 90
      - red: 0%
        blue: 100%
        green: 0%
        white: 0%
        num_leds: 90
  - addressable_scan:
      scan_width: 20
      move_interval: 20ms
  - addressable_twinkle:
  - addressable_fireworks:
  - addressable_flicker:
      name: Flicker

- platform: partition
  name: "Bottom"
  segments:
  - id: strip
    from: 150
    to: 178
  - id: strip
    from: 0
    to: 28
  effects:
  - addressable_scan:
      scan_width: 8
      move_interval: 33ms
- platform: partition
  name: "Left"
  segments:
  - id: strip
    from: 29
    to: 59
- platform: partition
  name: "Top"
  segments:
  - id: strip
    from: 60
    to: 118
  effects:
  - addressable_scan:
      scan_width: 8
      move_interval: 33ms
- platform: partition
  name: "Right"
  segments:
  - id: strip
    from: 119
    to: 149

i2c:

bme680_bsec:
  address: 0x77

sensor:
# BME680
- platform: bme680_bsec
  temperature:
    name: BME680 Temperature
    filters:
      - median
  humidity:
    name: BME680 Humidity
    filters:
      - median
  pressure:
    name: BME680 Pressure
    filters:
      - median
  iaq:
    id: iaq
    filters:
      - median

# DHT22
- platform: dht
  pin: GPIO32
  model: DHT22_TYPE2
  temperature:
    name: DHT22 Temperature
  humidity:
    name: DHT22 Humidity
    accuracy_decimals: 1

# Rotary Encoder
- platform: rotary_encoder
  pin_a: GPIO27 # brown
  pin_b: GPIO26
  id: knob
  name: Rotary Encoder
  restore_mode: ALWAYS_ZERO
  min_value: 0
  max_value: 31
  on_value:
    then:
    - light.turn_on:
        id: strip
        transition_length: 50ms
        brightness: !lambda "return x / 31;"

# Rotary Push Button
binary_sensor:
- platform: gpio
  pin:
    number: GPIO25
    inverted: true
  id: button
  filters:
  - delayed_on: 10ms
  - delayed_off: 10ms
  on_click:
    # Short press
    min_length: 50ms
    max_length: 350ms
    then:
    - if:
        condition:
          light.is_off: strip
        then:
        - sensor.rotary_encoder.set_value:
            id: knob
            value: 15
        else:
        - light.turn_off: strip
    # Double click
  # on_double_click:
  #   then:
  #   - script.execute: next_effect


text_sensor:
- platform: bme680_bsec
  iaq_accuracy:
    name: "BME680 IAQ Accuracy"

- platform: template
  name: "BME680 IAQ Classification"
  icon: "mdi:checkbox-marked-circle-outline"
  lambda: |-
    if ( int(id(iaq).state) <= 50) {
      return {"Excellent"};
    }
    else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
      return {"Good"};
    }
    else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
      return {"Lightly polluted"};
    }
    else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
      return {"Moderately polluted"};
    }
    else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
      return {"Heavily polluted"};
    }
    else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
      return {"Severely polluted"};
    }
    else if (int(id(iaq).state) >= 351) {
      return {"Extremely polluted"};
    }
    else {
      return {"error"};
    }

# # Globals
# globals:
# - id: current_effect_int
#   type: int
#   restore_value: no
#   initial_value: '0'

# # Automations
# script:
# - id: next_effect
#   then:
#   - script.execute: advance_effect
#   - script.execute: show_effect

# - id: advance_effect
#   then:
#   - lambda: |-
#       if (id(current_effect_int) < 3) {
#         id(current_effect_int) += 1;
#       } else {
#         id(current_effect_int) = 0;
#       }

# - id: show_effect
#   then:
#   - lambda: |-
#       auto call = id(strip).turn_on();

#       switch(id(current_effect_int)) {
#         default:
#           call.set_effect("Rainbow");
#           break;
#         case 1:
#           call.set_effect("Color Wipe");
#           break;
#         case 2:
#           call.set_effect("Scan");
#           break;
#         case 3:
#           call.set_effect("Pulse");
#           break;
#       }

#       call.perform();
