substitutions:
  devicename: rack
  devicename_upper: Rack

<<: !include ./.base.yaml

wifi:
  fast_connect: true
  manual_ip:
    static_ip: 192.168.188.80
    gateway: 192.168.188.1
    subnet: 255.255.255.0
    dns1: 192.168.188.4
    dns2: 192.168.188.4

## Fan Output (PWM)
output:
- platform: esp8266_pwm
  pin: D3
  frequency: 25000Hz
  id: fan_output

# ## Fan
fan:
- platform: speed
  output: fan_output
  name: "${devicename_upper} Fan"
  id: "${devicename}_fan"
  speed_count: 5

## LED
light:
- platform: neopixelbus
  type: GRB
  variant: WS2812
  pin: GPIO3
  num_leds: 1
  name: "${devicename_upper} Light"
  id: "${devicename}_led"
  effects:
  - pulse:
      name: "Fast pulse"
      transition_length: 0.5s
      update_interval: 0.5s

## I2C
i2c:
  sda: 4
  scl: 5
  scan: false

bme680_bsec:
  address: 0x77
  temperature_offset: 4
  sample_rate: lp

text_sensor:
- platform: bme680_bsec
  iaq_accuracy:
    name: "${devicename_upper} IAQ Accuracy"

sensor:
## BME680
- platform: bme680_bsec
  temperature:
    name: "${devicename_upper} Temperature"
    id: bme680_temp
    accuracy_decimals: 1
    on_value_range:

    ## < 24°C
    - below: 24.0
      then:
      - script.execute: led_blue   ## LED > blue

    ## < 26°C
    - below: 26.0
      then:
      - script.execute: fan_off    ## FAN > off

    ## 24°C - 28°C
    - above: 24.0
      below: 28.0
      then:
      - script.execute: led_green  ## LED > green

    ## 28°C - 30°C
    - above: 28.0
      below: 30.0
      then:
      - script.execute: led_yellow ## LED > yellow
      - script.execute: fan_low    ## FAN > low

    ## > 30°C
    - above: 30.0
      below: 32.0
      then:
      - script.execute: fan_med    ## FAN > medium

    ## > 32°C
    - above: 32.0
      then:
      - script.execute: led_red    ## LED > red
      - script.execute: fan_high   ## FAN > high

  pressure:
    name: "${devicename_upper} Pressure"
    accuracy_decimals: 2
  humidity:
    name: "${devicename_upper} Humidity"
    accuracy_decimals: 1
  gas_resistance:
    name: "${devicename_upper} Gas Resistance"
    accuracy_decimals: 1
  co2_equivalent:
    name: "${devicename_upper} CO²"


## Fan speed
- platform: pulse_counter
  pin: D4
  name: "${devicename_upper} Fan RPM"
  update_interval: 6s
  unit_of_measurement: rpm
  accuracy_decimals: 0
  icon: "mdi:fan"
  filters:
  - multiply: 0.5


## Automations
script:
  ## LED
  # - id: led_pulsate
  #   then:
  #   - light.turn_on:
  #       id: "${devicename}_led"
  #       red: 1
  #       blue: 1
  #       green: 0
  #       effect: pulse
  - id: led_blue
    then:
    - light.turn_on:
        id: "${devicename}_led"
        red: 0
        blue: 1
        green: 0
        brightness: .6
  - id: led_green
    then:
    - light.turn_on:
        id: "${devicename}_led"
        red: 0
        blue: 0
        green: 1
        brightness: .6
  - id: led_red
    then:
    - light.turn_on:
        id: "${devicename}_led"
        red: 1
        blue: 0
        green: 0
        brightness: .6
  - id: led_pink
    then:
    - light.turn_on:
        id: "${devicename}_led"
        red: 1
        blue: 1
        green: 0
        brightness: .6
  - id: led_yellow
    then:
    - light.turn_on:
        id: "${devicename}_led"
        red: 1
        blue: 0
        green: 1
        brightness: .6

  ## FAN
  - id: fan_off
    then:
    - fan.turn_off:
        id: "${devicename}_fan"
  - id: fan_low
    then:
    - fan.turn_on:
        id: "${devicename}_fan"
        speed: 1
  - id: fan_med
    then:
    - fan.turn_on:
        id: "${devicename}_fan"
        speed: 3
  - id: fan_high
    then:
    - fan.turn_on:
        id: "${devicename}_fan"
        speed: 5
