substitutions:
  devicename: rack
  devicename_upper: Rack

<<: !include ./.base.yaml

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename_upper} Fallback Hotspot"
    password: "OQMMDk93cB53"

captive_portal:

# Enable logging
logger:

# MQTT
mqtt:
  broker: "192.168.178.2"

# Enable Home Assistant API
api:

ota:

# Motion PIR
# binary_sensor:
# - platform: gpio
#   pin: D4
#   name: "Rack Movement"
#   device_class: motion

output:
- platform: esp8266_pwm
  pin: D3
  frequency: 25000 Hz
  id: my_output_1

## Fan
fan:
- platform: speed
  output: my_output_1
  name: "${devicename_upper} Fan"
  id: "${devicename}_fan"
  speed:
    low: 0.2     ## ca. 450rpm
    medium: 0.5  ## ca. 1100 rpm
    high: 0.8    ## ca. 1500 rpm

## LED
light:
- platform: neopixelbus
  type: GRB
  pin: GPIO3
  num_leds: 1
  name: "${devicename_upper} Light"
  id: "${devicename}_led"

## I2C
i2c:
  sda: 4
  scl: 5
  scan: True

sensor:
## BME680
- platform: bme680
  temperature:
    name: "${devicename_upper} Temperature"
    oversampling: 16x
    on_value_range:
    ## BELOW 24°C > Set LED to blue, turn off fan
    - below: 24.0
      then:
      - light.turn_on:
          id: "${devicename}_led"
          red: 0
          blue: 1
          green: 0
          brightness: .6
      - fan.turn_off:
          id: "${devicename}_fan"
    ## ABOVE 24°C > Set LED to GREEN
    - above: 24.0
      then:
      - light.turn_on:
          id: "${devicename}_led"
          red: 0
          blue: 0
          green: 1
          brightness: .6
    ## ABOVE 26°C > Set FAN speed to LOW
    - above: 26.0
      then:
      - fan.turn_on:
          id: "${devicename}_fan"
          speed: LOW
    ## BELOW 28°C > Set LED to green
    - below: 28.0
      then:
      - light.turn_on:
          id: "${devicename}_led"
          red: 0
          blue: 0
          green: 1
          brightness: .6
    ## ABOVE 28°C > Set LED to RED, set speed to MEDIUM
    - above: 28.0
      then:
      - light.turn_on:
          id: "${devicename}_led"
          red: 1
          blue: 0
          green: 0
          brightness: .6
      - fan.turn_on:
          id: "${devicename}_fan"
          speed: MEDIUM
    ## ABOVE 32°C > Set speed speed to HIGH
    - above: 32.0
      then:
      - fan.turn_on:
          id: "${devicename}_fan"
          speed: HIGH
  pressure:
    name: "${devicename_upper} Pressure"
  humidity:
    name: "${devicename_upper} Humidity"
  gas_resistance:
    name: "${devicename_upper} Gas Resistance"
  address: 0x77
  update_interval: 60s

## Fan speed
- platform: pulse_counter
  pin: D4
  name: "${devicename_upper} Fan RPM"
  update_interval: 5s
  unit_of_measurement: rpm
  accuracy_decimals: 0
  icon: "mdi:fan"
  filters:
  - multiply: 0.5


## Automations
