substitutions:
  devicename: stairs
  devicename_upper: Stairs
  timeout: 30s
  num_leds: "45"

<<: !include .base.yaml

binary_sensor:
  ## PIR
- platform: gpio
  pin: D1
  name: "${devicename_upper} Motion"
  device_class: motion
  on_press:
    then:
    - script.execute: stairs_leds

  ## Button
- platform: gpio
  pin:
    number: D5
    mode: INPUT_PULLUP
    inverted: true
  id: button
  on_press:
    if:
      condition:
      - script.is_running: stairs_leds
      then:
      - script.stop: stairs_leds
      - light.turn_off:
          id: strip
      else:
      - script.execute: stairs_leds

## LED Strip
light:
- platform: neopixelbus
  id: strip
  type: GRBW
  pin: GPIO3
  num_leds: "${num_leds}"
  name: "${devicename_upper} LED Strip"
  effects:
  - addressable_rainbow:
      width: 10
  - addressable_color_wipe:
      name: Police
      add_led_interval: 200ms
      colors:
      - red: 100%
        blue: 0%
        green: 0%
        white: 0%
        num_leds: 3
      - red: 0%
        blue: 100%
        green: 0%
        white: 0%
        num_leds: 3
  - addressable_scan:
  - addressable_twinkle:
  - addressable_fireworks:
  - addressable_flicker:
      name: Flicker

output:
- platform: gpio
  pin: D6
  id: led

sensor:
- platform: adc
  pin: A0
  id: lx
  name: "${devicename_upper} Lux"
  unit_of_measurement: lx
  update_interval: 5s
  filters:
  - lambda: |-
      return (x / 10000.0) * 2000000.0;
  on_raw_value:
    then:
    - if:
        condition:
          script.is_running: stairs_leds
        then:
        - light.turn_on:
            id: strip
            brightness: !lambda |-
              // output value will be in range 0.1 - 1.0
              if (x < 0.1) {
                return 0.1;
              } else if (x > 1) {
                return 1;
              }
              return x;

script:
- id: stairs_leds
  mode: restart
  then:
    - light.turn_on:
        id: strip
        brightness: !lambda |-
          // output value wull be in range 0.1 - 1.0
          if (id(lx).raw_state < 0.1) {
            return 0.1;
          } else if (id(lx).raw_state > 1) {
            return 1;
          }
          return id(lx).raw_state;
    - delay: ${timeout}
    - light.turn_off: strip