substitutions:
  devicename: stairs
  devicename_upper: Stairs
  timeout: 30s
  step_delay: 0.2s
  motion_delay: 5s
  num_leds: "45"

<<: !include .base.yaml

wifi:
  fast_connect: true
  manual_ip:
    static_ip: 192.168.188.81
    gateway: 192.168.188.1
    subnet: 255.255.255.0
    dns1: 192.168.188.4
    dns2: 192.168.188.4

globals:
- id: gwhite
  type: double
  restore_value: no
  initial_value: '0.4'

binary_sensor:
  ## PIR
- platform: gpio
  pin: D1
  name: "${devicename_upper} Motion"
  device_class: motion
  # on_press:
  #   then:
  #   - script.execute: stairs_leds

  ## Button
- platform: gpio
  pin:
    number: D5
    mode: INPUT_PULLUP
    inverted: true
  id: button
  on_press:
    if:
      condition:
      - script.is_running: stairs_leds
      then:
      - script.stop: stairs_leds
      - light.turn_off:
          id: strip
      else:
      - light.turn_off: strip
      - script.execute: stairs_leds

## LED Strip
light:
- platform: neopixelbus
  variant: SK6812
  type: GRBW
  pin: GPIO3
  num_leds: "${num_leds}"
  id: strip
  name: "${devicename_upper} LED Strip"
  restore_mode: ALWAYS_OFF
  effects:
  - addressable_rainbow:
      width: 45
  - addressable_color_wipe:
      name: Police
      add_led_interval: 50ms
      colors:
      - red: 100%
        blue: 0%
        green: 0%
        white: 0%
        num_leds: 15
      - red: 0%
        blue: 100%
        green: 0%
        white: 0%
        num_leds: 15
  - addressable_scan:
      scan_width: 3
      move_interval: 20ms
  - addressable_twinkle:
  - addressable_fireworks:
  - addressable_flicker:
      name: Flicker
- platform: partition
  id: step1
  segments:
  - id: strip
    from: 0
    to: 14
- platform: partition
  id: step2
  segments:
  - id: strip
    from: 15
    to: 29
    reversed: true
- platform: partition
  id: step3
  segments:
  - id: strip
    from: 30
    to: 44

sensor:
- platform: adc
  pin: A0
  id: brightness
  name: "${devicename_upper} Lux"
  unit_of_measurement: lx
  update_interval: 5s
  filters:
  - multiply: 200
  # on_raw_value:
  #   ## Store current brightness value in global variable
  # - globals.set:
  #     id: gwhite
  #     value: !lambda |-
  #       if (x < 0.1) {
  #         return (double) 0.1;
  #       } else if (x > 1) {
  #         return (double) 1;
  #       }
  #       return (double) (x);

script:
- id: stairs_leds
  mode: restart
  then:
    ## Turn on the lights in proper order
  - light.turn_on: &color
      id: step1
      color_mode: RGB_WHITE
      brightness: 1
      color_brightness: 0 ## Required to keep the RGB leds off
      white: 0.4
      red: 0
      blue: 0
      green: 0
      # white: !lambda |-
      #   return id(gwhite);
      # brightness: !lambda |-
      #   return id(gwhite);
  - delay: ${step_delay}
  - light.turn_on:
      <<: *color
      id: step2
  - delay: ${step_delay}
  - light.turn_on:
      <<: *color
      id: step3

    ## Wait a few seconds
  - delay: ${motion_delay}

    ## Start turning things off again
  - light.turn_off: step1
  - delay: ${step_delay}
  - light.turn_off: step2
  - delay: ${step_delay}
  - light.turn_off: step3
