substitutions:
  devicename: stairs
  devicename_upper: Stairs

  ## Number of LEDs in strip (15 per stair)
  num_leds: "45"

  ## Time between toggling on/off the stairs
  step_delay: 0.5s

<<: !include .base32.yaml

wifi:
  fast_connect: true

binary_sensor:
  ## PIR
- platform: gpio
  pin: GPIO18
  name: "${devicename_upper} Motion"
  device_class: motion
  on_press:
    if:
      condition: 
        not:
        - light.is_on: strip
      then:
      - script.execute: 
          id: stairs_leds
          ## Motion events activate light for 10s
          delay_ms: 10000

  ## Button
- platform: gpio
  pin:
    number: GPIO5
    mode: INPUT_PULLUP
    inverted: true
  id: button
  on_press:
    if:
      condition:
      - script.is_running: stairs_leds
      then:
      - script.stop: stairs_leds
      - light.turn_off:
          id: strip
      else:
      - light.turn_off:
          id: strip
          transition_length: 0s
      - script.execute: 
          id: stairs_leds
          ## Button presses activate light for 30s
          delay_ms: 30000

## LED Strip
light:
- platform: neopixelbus
  variant: SK6812
  type: GRBW
  pin: GPIO4
  num_leds: "${num_leds}"
  id: strip
  name: "${devicename_upper} LED Strip"
  restore_mode: ALWAYS_OFF
  effects:
  - addressable_rainbow:
      width: 45
  - addressable_color_wipe:
      name: Police
      add_led_interval: 50ms
      colors:
      - red: 100%
        blue: 0%
        green: 0%
        white: 0%
        num_leds: 15
      - red: 0%
        blue: 100%
        green: 0%
        white: 0%
        num_leds: 15
  - addressable_scan:
      scan_width: 3
      move_interval: 20ms
  - addressable_twinkle:
  - addressable_fireworks:
  - addressable_flicker:
      name: Flicker
- platform: partition
  id: step1
  segments:
  - id: strip
    from: 0
    to: 14
- platform: partition
  id: step2
  segments:
  - id: strip
    from: 15
    to: 29
    reversed: true
- platform: partition
  id: step3
  segments:
  - id: strip
    from: 30
    to: 44

script:
- id: stairs_leds
  mode: restart
  parameters:
    delay_ms: int
  then:
    ## Turn on the lights in proper order
  - light.turn_on: &color
      id: step1
      transition_length: 0.3s
      color_mode: RGB_WHITE
      brightness: 0.4
      white: 1.0
      color_brightness: 0 ## Required to keep the RGB leds off
      red: 0
      blue: 0
      green: 0
  - delay: ${step_delay}
  - light.turn_on:
      <<: *color
      id: step2
  - delay: ${step_delay}
  - light.turn_on:
      <<: *color
      id: step3

    ## Wait a few seconds
  - delay: !lambda return delay_ms;

    ## Start turning things off again
  - light.turn_off: step1
  - delay: ${step_delay}
  - light.turn_off: step2
  - delay: ${step_delay}
  - light.turn_off: step3
